# Site settings
# 这里是jekyll模版的参数调节部分
title: Fourous
SEOTitle: fourous
header-img: img/home-bg.jpg
email: fourousky@gmail.com
description: "C’est la vie."
keyword: "github,fourous,java,设计模式,skyWalking,grafana"
url: "http://Fourous.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Fourous/Fouorus.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "成功不必在我，而功力不必唐捐"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
zhihu_username:     fourous
github_username:    Fourous


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

plugins:
  - jekyll-paginate
paginate: 5



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e0cd032719e0837d1098                            #生成的clientID
  clientSecret: 94fa8c05b6f4b780e0d69ba3a750a2ef9e7c06ac   #生成的clientSecret
  repo: Fourous.github.io    #仓库名称
  owner: Fourous    #github用户名
  admin: Fourous
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 边栏的Friends外链
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "知乎",
        href: "https://www.zhihu.com/people/fourous"
    }
]
